<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'raisonSocial', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'datecreation', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'matriculeFiscal', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'refenrenceEntre'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'raisonSocial', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'datecreation', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'matriculeFiscal', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'refenrenceEntre'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $Prenom): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$Prenom]);

        return parent::setPrenom($Prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonSocial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonSocial', []);

        return parent::getRaisonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonSocial(string $raisonSocial): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonSocial', [$raisonSocial]);

        return parent::setRaisonSocial($raisonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', []);

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation(\DateTimeInterface $datecreation): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', [$datecreation]);

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculeFiscal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculeFiscal', []);

        return parent::getMatriculeFiscal();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculeFiscal(string $matriculeFiscal): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculeFiscal', [$matriculeFiscal]);

        return parent::setMatriculeFiscal($matriculeFiscal);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel(string $tel): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefenrenceEntre(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefenrenceEntre', []);

        return parent::getRefenrenceEntre();
    }

    /**
     * {@inheritDoc}
     */
    public function addRefenrenceEntre(\App\Entity\ReferenceEntre $refenrenceEntre): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRefenrenceEntre', [$refenrenceEntre]);

        return parent::addRefenrenceEntre($refenrenceEntre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRefenrenceEntre(\App\Entity\ReferenceEntre $refenrenceEntre): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRefenrenceEntre', [$refenrenceEntre]);

        return parent::removeRefenrenceEntre($refenrenceEntre);
    }

}
