<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \App\Entity\Article implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'qtePP', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'prixAchat', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'prixVente', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'qteMax', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'gteMin', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'famille', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'qteStock', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'magazins', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'ventes', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'achat'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'qtePP', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'prixAchat', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'prixVente', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'qteMax', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'gteMin', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'famille', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'qteStock', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'magazins', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'ventes', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'achat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Article $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation(string $designation): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$designation]);

        return parent::setDesignation($designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtePP(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtePP', []);

        return parent::getQtePP();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtePP(int $qtePP): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtePP', [$qtePP]);

        return parent::setQtePP($qtePP);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixAchat(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixAchat', []);

        return parent::getPrixAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixAchat(int $prixAchat): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixAchat', [$prixAchat]);

        return parent::setPrixAchat($prixAchat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixVente(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixVente', []);

        return parent::getPrixVente();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixVente(int $prixVente): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixVente', [$prixVente]);

        return parent::setPrixVente($prixVente);
    }

    /**
     * {@inheritDoc}
     */
    public function getQteMax(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQteMax', []);

        return parent::getQteMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setQteMax(int $qteMax): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQteMax', [$qteMax]);

        return parent::setQteMax($qteMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getGteMin(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGteMin', []);

        return parent::getGteMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setGteMin(int $gteMin): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGteMin', [$gteMin]);

        return parent::setGteMin($gteMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamille(): ?\App\Entity\Famille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamille', []);

        return parent::getFamille();
    }

    /**
     * {@inheritDoc}
     */
    public function setFamille(?\App\Entity\Famille $famille): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFamille', [$famille]);

        return parent::setFamille($famille);
    }

    /**
     * {@inheritDoc}
     */
    public function getQteStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQteStock', []);

        return parent::getQteStock();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setQteStock($qteStock): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQteStock', [$qteStock]);

        parent::setQteStock($qteStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getMagazins(): ?\App\Entity\Magazin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagazins', []);

        return parent::getMagazins();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagazins(?\App\Entity\Magazin $magazins): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagazins', [$magazins]);

        return parent::setMagazins($magazins);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentes', []);

        return parent::getVentes();
    }

    /**
     * {@inheritDoc}
     */
    public function addVente(\App\Entity\Vente $vente): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVente', [$vente]);

        return parent::addVente($vente);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVente(\App\Entity\Vente $vente): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVente', [$vente]);

        return parent::removeVente($vente);
    }

    /**
     * {@inheritDoc}
     */
    public function getAchat(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAchat', []);

        return parent::getAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function addAchat(\App\Entity\Achat $achat): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAchat', [$achat]);

        return parent::addAchat($achat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAchat(\App\Entity\Achat $achat): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAchat', [$achat]);

        return parent::removeAchat($achat);
    }

}
