<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsQJGC7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsQJGC7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWsQJGC7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWsQJGC7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWsQJGC7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WsQJGC7',
    'container.build_id' => '146efcf3',
    'container.build_time' => 1591487147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsQJGC7');
